// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CalcButton: typeof import('./src/components/calc/button/index.vue')['default']
    CalcCheckbox: typeof import('./src/components/calc/checkbox/index.vue')['default']
    CalcDialog: typeof import('./src/components/calc/dialog/index.vue')['default']
    CalcMenuMenu: typeof import('./src/components/calc/menu/menu.vue')['default']
    CalcOption: typeof import('./src/components/calc/option/index.vue')['default']
    CalcSelect: typeof import('./src/components/calc/select/index.vue')['default']
    CalcTab: typeof import('./src/components/calc/tab/index.vue')['default']
    CalcTabs: typeof import('./src/components/calc/tabs/index.vue')['default']
    CalcTooltip: typeof import('./src/components/calc/tooltip/index.vue')['default']
  }
}

export { }
